name: Jarvis PyQt5 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint Python files
      run: |
        # Adjust excludes based on your project structure
        flake8 . --exclude=venv,__pycache__,.git,.github --max-line-length=120

    - name: Run unit tests
      run: |
        pytest tests/
